apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ready-orca-python 
  janus-idp.io/tekton: ready-orca-python
  backstage.io/kubernetes-id: ready-orca-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: ready-orca-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  